'use client'

function SparkleIcon({ className = '' }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
      <path d="M12 3l1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5L12 3z" />
      <path d="M5 19l1.5-3L10 17.5 8.5 14 5 15.5l3-1.5z" />
      <path d="M19 19l-1.5-3L14 17.5l1.5-3.5L19 15.5l-3 1.5z" />
    </svg>
  )
}

export default function ReasoningCard({ farm_id, reasoning }) {
  return (
    <div
      className="dashboard-card relative flex flex-col overflow-hidden bg-[#f5f0e8] text-deep-green"
      style={{ borderLeft: '3px solid #d4a843' }}
    >
      <div className="flex items-center gap-1.5">
        <SparkleIcon className="h-3.5 w-3.5 text-gold" />
        <p className="card-header-label text-deep-green/70">Reasoning</p>
      </div>
      <p
        className="reasoning-text mt-1.5 flex-1 text-[13px] leading-[1.6] text-deep-green/90 line-clamp-4"
        style={{ fontSize: '13px', lineHeight: 1.6 }}
      >
        {reasoning ?? '—'}
      </p>
      <p className="mt-2 text-right text-[10px] text-deep-green/50">
        Generated by Claude AI
      </p>
    </div>
  )
}
